buildTasks:

  - name: 'test for artifacts'
    commands:
      - echo 'executing step < test for artifacts >'
      - npm install
#      - tar zcvf package.tar.gz --exclude=*.tar.gz *
    agent:
      queue: 'pubsub-dev'
    artifacts: 'package.tar.gz'

  - name: 'unit test'
    commands:
#      - buildit-agent artifacts download buildid=xxx step=package files=*
      - echo 'executing step < unit test >'
      - ping localhost -w 5
    agents:
      queue: 'pubsub-dev'
    dependsOn:
      - 'test for artifacts'
    fetchArtifacts:
      - task: 'test for artifacts'
        artifacts: 'package.tar.gz'

  - name: 'deploy dev environment'
    commands:
      - echo 'executing step < deploy dev environment >'
      - ping localhost -w 5
    agents:
      queue: 'pubsub-dev'
    dependsOn:
      - 'install dependencies'

  - name: 'integration test'
    commands:
      - echo 'executing step < integration test >'
      - ping localhost -w 5
    agents:
      queue: 'pubsub-dev'
    dependsOn:
      - 'deploy dev environment'

  - name: 'api test'
    commands:
      - echo 'executing step < api test >'
      - ping localhost -w 5
    agents:
      queue: 'pubsub-dev'
    dependsOn:
      - 'deploy dev environment'

  - name: 'end to end test'
    commands:
      - echo 'executing step < end to end test >'
      - ping localhost -w 5
    agents:
      queue: 'pubsub-dev'
    dependsOn:
      - 'deploy dev environment'

  - name: 'deploy production'
    commands:
      - echo 'executing step < integration test >'
      - ping localhost -w 5
    agents:
      queue: 'pubsub-dev'
    depends-on:
      - 'unit test'
      - 'integration test'
      - 'api test'
      - 'end to end test'
    branch: 'master'

  - name: 'smoke test'
    commands:
      - echo 'executing step < integration test >'
      - ping localhost -w 5
    agents:
      queue: 'pubsub-dev'
    dependsOn:
      - 'deploy production'
    branch: 'master'